version: "3.8"
services:
  app_setup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: >
      sh -c "
        if [ '${APP_NAME}' ] && [ '${MODELS_DATA}' ]; then
          mkdir -p scripts &&
          chmod +x /app/scripts/generate_angular_files.sh &&
          echo 'Generating Angular files for models: ${MODELS_DATA}' &&
          /app/scripts/generate_angular_files.sh \"${APP_NAME}\" \"${MODELS_DATA}\";
        else
          echo 'No APP_NAME or MODELS_DATA provided. Skipping code generation.';
        fi
      "

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
        echo 'Starting Angular development server...' &&
        ng serve --host 0.0.0.0 --disable-host-check
      "
    env_file:
      - .env
    depends_on:
      - app_setup
